format = '''
┌──\[$username@$shell\] $directory$git_branch$hostname
└─$character '''


add_newline = true

[username]
format = '[$user](bold yellow)'
show_always = true

[shell]
disabled = false
format = '[$indicator](bold 2)'

[directory]
read_only = ' 󰌾'
format = '[$path](bold blue)[$read_only](bold yellow)'
truncation_length = 0

[git_branch]
symbol = ' '
format = '[$symbol](green)'

[hostname]
ssh_only = true
format = ' on [$hostname](bold red)'

[character]
format = '[\$](cyan)'
