# Not good enough, to redo everything


format = '''$username$env_var$directory$git_branch$hostname$character '''

add_newline = false


[directory]
read_only = ' 󰌾'
format = '[$path](bold blue)[$read_only](bold yellow) '
truncation_length = 0

[git_branch]
symbol = ''
format = '[$symbol](green) '

[hostname]
ssh_only = true
format = '[$ssh_symbol](bold blue) on [$hostname](bold red) '

[character]
format = '[\$](cyan)'

[env_var]
variable = 'TMUX_ENV'
default = '<>'
format = '[$env_value](bold red) '
